### ISSUE TITLE
Possible topics from quantecon 2019

### ISSUE THREAD

**Issue by oyamad** [OyamaZemi/StudyNotes#22]
* [x] [Job Search III: Search with Learning](https://lectures.quantecon.org/py/odu.html)
* [x] [Job Search IV: Modeling Career Choice](https://lectures.quantecon.org/py/career.html)
* [ ] [Job Search V: On-the-Job Search](https://lectures.quantecon.org/py/jv.html)
* [x] [The Aiyagari Model](https://lectures.quantecon.org/py/aiyagari.html)
* [x] [Default Risk and Income Fluctuations](https://lectures.quantecon.org/py/arellano.html)
* [ ] [Globalization and Cycles](https://lectures.quantecon.org/py/matsuyama.html)
* [x] [Coase’s Theory of the Firm](https://python.quantecon.org/coase.html)
* [x] [Von Neumann Growth Model (and a Generalization)](https://lectures.quantecon.org/py/von_neumann_model.html)
* [ ] [Competitive Equilibria of Chang Model](https://lectures.quantecon.org/py/chang_ramsey.html)
* [x] [LQ Control: Foundations](https://lectures.quantecon.org/py/lqcontrol.html)
* [ ] [Robustness](https://lectures.quantecon.org/py/robustness.html)
* [ ] [A First Look at the Kalman Filter](https://lectures.quantecon.org/py/kalman.html)
* [x] [Uncertainty Traps](https://lectures.quantecon.org/py/uncertainty_traps.html)
* [x] [Asset Pricing I: Finite State Models](https://lectures.quantecon.org/py/markov_asset.html)
* [x] [Asset Pricing II: The Lucas Asset Pricing Model](https://lectures.quantecon.org/py/lucas_model.html)
* [ ] [Asset Pricing III: Incomplete Markets](https://lectures.quantecon.org/py/harrison_kreps.html)
* [x] [Schelling’s Segregation Model](https://python.quantecon.org/schelling.html)

**Comment by YumaAoki** [comment]
Job-Searchの3をやります

**Comment by Alalalalaki** [comment]
6/17 : Job Search IV

**Comment by oyamad** [comment]
Job Search IV については，[`DiscreteDP` クラスを使ったバージョン](https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/ddp_ex_career_py.ipynb)も参照してください．

**Comment by Alalalalaki** [comment]
> Job Search IV については，[`DiscreteDP` クラスを使ったバージョン](https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/ddp_ex_career_py.ipynb)も参照してください．

承知致しました。

**Comment by tuttugu-ryo** [comment]
今週月曜の授業内でExercise 1のグラフは@njitありとなしとで走査時間が変わらないと発表したのですが、それは僕の勘違いでした。申し訳ありません。

**Comment by Smith-yourbestfriend** [comment]
6/24　Globalization and Cyclesやります

**Comment by Yuya-Furusawa** [comment]
7/1 Chang Modelやります

**Comment by Yuya-Furusawa** [comment]
すいません、明日（2019/07/01）Chang ModelではなくUncertainty Trapsやります。
Chang Model思っていたより時間がかかりそうなので次回にさせてください。
申し訳ないです。

**Comment by Smith-yourbestfriend** [comment]
明日(7/1)はGlobal Cycleのコードをやる予定でしたが、体調を崩してしまったので来週 (7/8)にさせていただけると助かります。

**Comment by oyamad** [comment]
@Smith-yourbestfriend はい了解です．おだいじに．

**Comment by hinayuki64** [comment]
7/8 Aiyagari

**Comment by YumaAoki** [comment]
7/10 Default Risk and Income Fluctuations

**Comment by tuttugu-ryo** [comment]
7/22 Von Neumann Growth Moldelをやります

**Comment by YumaAoki** [comment]
ご無沙汰しております。
Quanteconから外れてしまいますがゼミ対抗フットサル大会のチーム募集があったのでご連絡です。
日程は10/12(土)で、募集期限は9/1(日)23:59とのことです。
一応確認ですが、参加申請をしてしまっても良いでしょうか？

**Comment by Smith-yourbestfriend** [comment]
10/7  Coase’s theory of the firm やります
直前に農学部の授業を取っているので少し遅くなります

**Comment by Alalalalaki** [comment]
10/21 Hopenhayn modelをやります。Hopenhayn (1992, ecma)と Hopenhayn & Rogerson (1993, JPE)を参照してください。

Note: https://nbviewer.jupyter.org/github/Alalalalaki/Econ-Model-Notes/blob/master/Macro/Hopenhayn.ipynb

**Comment by Yuya-Furusawa** [comment]
10/30
- [Recursive Repeated Games(Julia)](https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/recursive_repeated_games.ipynb)
    -  MOIとのcompatibilityをチェック
    - Game.jlがそもそも動くかを確認
- [The Nelder-Mead Algorithm(Python)](https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/chase_nelder_mead.ipynb)
    - scipyとか見て他のalgorithmとの比較をする

~~**できる方を**をやります！~~ → Recursive Repeated Games(Julia)やります

[note](https://nbviewer.jupyter.org/github/Yuya-Furusawa/Self-Study/blob/master/oyamasemi/recursive_repeated_games_oyamasemi.ipynb)
[Slide](https://github.com/Yuya-Furusawa/Self-Study/blob/master/oyamasemi/repeated_game.pdf)


11/2 追記
発表の時は出来ませんでしたが、Pull Requestをおくって元のコードを修正したので、アルゴリズムの収束をplotできました
![newplot](https://user-images.githubusercontent.com/35675799/68043394-842b8d80-fd18-11e9-9e41-28de19f9be02.png)

**Comment by hinayuki64** [comment]
11/4
Brouwer’s fixed point theorem: Sperer's Lemma
三辺が0,1,2の三角形を探すプログラムを作ってみよう　後編

昨年度の夏合宿でやったネタですが、完全版として発表します。
不動点定理のざっくりとした説明からやるつもりです。

**Comment by hinayuki64** [comment]
すみません、本日のゼミですが、10分ほど遅刻します。発表担当なのに申し訳ありませんが、よろしくお願いいたします。

**Comment by YumaAoki** [comment]
11/7
都市の移動解析
領域から領域までの移動量を、人口や移動コストを用いて記述しようという取り組みです。

https://drive.google.com/drive/folders/1FGcPRrNrmUu-1c39Oo2SGdMrZ2sOLoQD?usp=sharing
コードとスライドを取り急ぎググドラに掲載しました。ECCSのアドレスから参照してください。
あとで適切にアップロードします

参考文献：栗田治(2013) 都市と地域の数理モデル 共立出版

**Comment by tuttugu-ryo** [comment]
11/18 QuantEconのAsset Pricing I: Finite State Modelsやります

**Comment by Smith-yourbestfriend** [comment]
LQ dynamic programming modelやります

**Comment by Alalalalaki** [comment]
12/2 Solow modelをやります。[Note](https://nbviewer.jupyter.org/github/Alalalalaki/Econ-Model-Notes/blob/master/Macro/Solow.ipynb)。

**Comment by Yuya-Furusawa** [comment]
12/9は修論の発表をさせてください
プログラミングはほとんど関係ないですが...

[Slide](https://github.com/Yuya-Furusawa/Self-Study/blob/master/endo_net/endo_net_slide.pdf)
[Paper(draft)](https://github.com/Yuya-Furusawa/Self-Study/blob/master/endo_net/endo_net.pdf)

**Comment by hinayuki64** [comment]
12/16  卒論発表 「クラブコンバットのゲーム理論的分析」
1時間くらいで終わる可能性もあるので、次の人もできれば準備お願いします。

**Comment by hinayuki64** [comment]
すみません、都合により準備が間に合わないため、卒論発表は @YumaAoki と @tuttugu-ryo のあと、12/23 or 25にさせていただきます(彼らの了承済みです)。
申し訳ありませんがよろしくお願いいたします。

**Comment by tuttugu-ryo** [comment]
12/16　@YumaAoki の後、Asset Pricing II: The Lucas Asset Pricing Modelやります。
その前後で来年度のテキストも決定したいです。

**Comment by YumaAoki** [comment]
12/23? 非集計ロジットモデル
本日発表予定でしたが体調不良のため欠席し、次回以降で発表させていただければと思います(柴田君の了承済みです)
