### ISSUE TITLE
Possible topics from quantecon 2021

### ISSUE THREAD

**Issue by oyamad** [OyamaZemi/StudyNotes#23]
Quantitative Economics with Python

* [x] [Modeling COVID 19](https://python.quantecon.org/sir_model.html)
* [x] [Finite Markov Chains](https://python.quantecon.org/finite_markov.html)
* [x] [Shortest Paths](https://python.quantecon.org/short_path.html)
* [x] [Job Search I: The McCall Search Model](https://python.quantecon.org/mccall_model.html)
* [ ] [Job Search II: Search and Separation](https://python.quantecon.org/mccall_model_with_separation.html)
* [ ] [Job Search III: Fitted Value Function Iteration](https://python.quantecon.org/mccall_fitted_vfi.html)
* [ ] [Job Search IV: Correlated Wage Offers](https://python.quantecon.org/mccall_correlated.html)
* [x] [Job Search V: Modeling Career Choice](https://python.quantecon.org/career.html)
* [x] [Job Search VI: On-the-Job Search](https://python.quantecon.org/jv.html)
* [ ] [Job Search VII: Search with Learning](https://python.quantecon.org/odu.html)
* [x] [Cake Eating I: Introduction to Optimal Saving](https://python.quantecon.org/cake_eating_problem.html)
* [x] [Cake Eating II: Numerical Methods](https://python.quantecon.org/cake_eating_numerical.html)
* [ ] ...
* [ ] [Schelling’s Segregation Model](https://python.quantecon.org/schelling.html)
* [x] [A Lake Model of Employment and Unemployment](https://python.quantecon.org/lake_model.html)
* [ ] ...
* [ ] [Asset Pricing: Finite State Models]()
* [ ] [Competitive equilibria with Arrow securities]()
* [ ] [Heterogeneous Beliefs and Bubbles]()
* [ ] ...

Advanced Quantitative Economics with Python

* [ ] [Discrete State Dynamic Programming](https://python-advanced.quantecon.org/discrete_dp.html)
* [ ] [Asset Pricing II: The Lucas Asset Pricing Model](https://python-advanced.quantecon.org/lucas_model.html)
* [ ] ...
* [ ] [Competitive Equilibria of a Model of Chang](https://python-advanced.quantecon.org/chang_ramsey.html)
* [ ] ...

Quantitative Economics with Julia

* [ ] [Markov Perfect Equilibrium](https://julia.quantecon.org/multi_agent_models/markov_perf.html)

@OyamaZemi/2021

**Comment by kuramogura** [comment]
6/14のfinite markov chain, shortest pathsは全員が一通り予習しておき、その場で回していくという方法でやります。
それ以降は、倉持はCOVID-19のモデル改良とJob searchを担当します。

**Comment by oyamad** [comment]
"Quantitative Economics with Python" のレクチャーで issue や pull request を出すのはこちら：
https://github.com/QuantEcon/lecture-python.myst

**Comment by tetrapod54** [comment]
53. Asset Pricing: Finite State Models　を7/5に発表しようかと思います。

**Comment by tetrapod54** [comment]
また、月曜日（6/21)の発表の際に、修正した方がよさそうな箇所をまとめました。


19 Shortest Path の修正した方がよさそうな点です。

* [x] Solving for Minimum cost-to-goのimplementationにおいて
  Numpy = 1.2ではnp.intではなくintを使う。

* [ ] Exercise1の最初のコード　
  Openを使うときは、withを使う。

* [x] Exercise1の最初のコード
  ```py
  Q = np.ones((num_nodes, num_nodes))
  Q = Q * np.inf 
  ```
  を
  ```py
  Q = np.full((num_nodes, num_nodes),np.inf)
  ```
  とする。

* [x] compute_cost_to_go(Q)について
  `
  num_nodes=Q.shape[0] #本来は変数が定義されていなかったが、たまたまグローバル変数と同じ名前だったので正常に動いた。`

* [x] compute_cost_to_go(Q)について
  ``` py
  next_J = np.empty(num_nodes)  #next_Jの初期値を使うことはないから、 変数を定義する必要がない。
  ```

* [x] print_best_path(J, Q)
  ```py
  sum_costs += Q[current_node, next_node] #J[0]=sum_costになるのでsum_costを定義する必要がない
  ```

**Comment by tetrapod54** [comment]
自分はちょっと今忙しいので手をつけれないのですが、7月中旬になれば多少手が空くと思います。なので、それまでに誰もやっていなければ私が修正しようかと思っています。

**Comment by oyamad** [comment]
せっかくなので，今日授業中時間をとってみんなでそれぞれやってみましょう．

**Comment by kuramogura** [comment]
連絡が遅くなってしまいましたが、本日は所用により参加できません。申し訳ありません。

**Comment by Jaxon280** [comment]
報告が遅れてしまいましたが、Julia version の Markov Perfect Equilibrium を 7/12に発表しようかと思います。本体の発表の前に軽く Julia についても触れる予定にします。

**Comment by oyamad** [comment]
これは私が報告しておきました：
* [x] [short_path] 画像が表示されない

(EDIT: 修正されました)

**Comment by tetrapod54** [comment]
前回の授業の最後で、Asset Pricing: Finite State Modelsを少し扱ったのですが、自分のレベルを超えていると感じたので、取り扱う題材を変えようかと思っています。
次回の授業では、Job Search I: The McCall Search Modelをやろうと思います。

**Comment by oyamad** [comment]
* [ ] `np.ones` のパターンを `np.full` に書きかえるのは，レクチャーの方はほぼ終わっていますが，[QuantEcon.py](https://github.com/QuantEcon/QuantEcon.py) ライブラリの方の https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/quad.py に2か所残っています．やれる人はやってみてください．
